### ISSUE TITLE
[Feature]: Compatibility with Rubidium/Sodium

### ISSUE THREAD

**Issue by TheIllusiveC4** [TheIllusiveC4/CustomFoV#10]
### What is the new feature or improvement?

I received reports that Custom FoV's options are not available in 1.19.2 with Rubidium/Sodium so this is something that I'll need to investigate further and hopefully add compatibility.

**Comment by The-Arcanian** [comment]
It is not just on 1.19.2, it is on 1.18.2 as well.
![image](https://user-images.githubusercontent.com/7005184/227817293-a5bdaa7c-24f0-4146-b6b0-0f019b76939a.png)
![image](https://user-images.githubusercontent.com/7005184/227817357-331413f7-5d47-41f1-bbd0-8b2a1f28a09f.png)
You can access them through the config menu though (with Configured at least).
![image](https://user-images.githubusercontent.com/7005184/227817603-80d84ae8-f2c9-4fc4-9c78-8c7683b86ae6.png)

**Comment by Momoirosch** [comment]
In 1.19.2 you cant use configured to change it (there is no config, not even in the config folder....)

**Comment by Momoirosch** [comment]
Okay you can change it in the options.txt file in your modpack folder

**Comment by TheIllusiveC4** [comment]
It turns out the initial reports that I used to file this was simply a case of misunderstanding, and the same is the case for the comments above. For future reference:

On 1.18.2 and below, Custom FoV uses configuration files to change its settings, located in the `config` folder.

On 1.19.2 and above, Custom FoV uses the options located in Video Settings and Accessibility Settings of the in-game menu.
