### ISSUE TITLE
I dont have the sliders at all, and vanillas doesnt work

### ISSUE THREAD

**Issue by Aceplante** [TheIllusiveC4/CustomFoV#13]
### Minecraft Version

1.18.2

### What happened?

Title. I dont have the 6 sliders shown in the screenshot

### How do you trigger this bug?

1.
2.
3.
...

### Loader

Forge

### Loader Version

latest one

### Mod Version

1.18.2

**Comment by TheIllusiveC4** [comment]
The 1.18.2 version uses the configuration file `customfov-client.toml` located in the `config` folder instead.
