### ISSUE TITLE
[1.15.2] Going underwater makes everything on screen go upside down + texture seizure.

### ISSUE THREAD

**Issue by Gbergz** [TheIllusiveC4/CustomFoV#2]
#### Versions:
* Custom FoV: 1.15.2-3.0
* Forge: 31.1.0

#### Steps to Reproduce:
1. Spawn into a world.
2. Step into 2 blocks deep water.
3. Observe.
.. **blind.**

Edit: Here's a preview: https://gyazo.com/d3674e94f10b70e069c717bfe1bfe7f7
And being upside down: https://gyazo.com/614650be1405686dfbec6418a6072823
Crash Log: No crash logs.

**Comment by TheIllusiveC4** [comment]
I can't reproduce this. What are your config settings? If they're default, then do you have any other mods installed?

**Comment by Gbergz** [comment]
I've reproduced this on a clean instance with default settings.
EDIT: Actually not completely default. Changed the FOV to 80. (Sorry.)

**Comment by TheIllusiveC4** [comment]
Ah ok, changing the FoV to 80 reproduces it. I'll look into a fix.

**Comment by Gbergz** [comment]
Appears the same issue is present on the 1.14.4 version. Any FOV over 80 makes your arm 2 meters long & turns your view upside down and also it has another texture seizure.

EDIT: Also 'Normal' FOV turns the arm 2 meters long aswell. And the FOV doesn't seem normal.

**Minecraft**: 1.14.4
**Forge**: 28.2.0
**CustomFov**: 1.14.4-2.0

**Comment by TheIllusiveC4** [comment]
I can reproduce the same issue from 1.15.2, likely from the same bug in the code. However, I can't reproduce the "turning arm 2 meters long" aspect, and 'Normal' FoV seems normal to me. Are you testing that on a clean instance also?

**Comment by Gbergz** [comment]
Yes i'm on a clean instance. Look here at the arm in water here:
![2020-02-14_21 52 49](https://user-images.githubusercontent.com/26634554/74566743-75d64a00-4f74-11ea-9bc0-65fc2ad499e1.png)

Normal Arm:
![2020-02-14_21 53 51](https://user-images.githubusercontent.com/26634554/74566760-838bcf80-4f74-11ea-98da-a2bda624add4.png)

The arm issue is also fixed on the 1.15.2 version.
Along with the FoV issue, thanks for that btw. :)

**Comment by TheIllusiveC4** [comment]
Oh okay, I understand now. I just put out the same fix for 1.14.4 as 1.15.2 so the issue should be resolved on both ends.

**Comment by Gbergz** [comment]
Thanks for the quick updates, much appreciated! :)
