### ISSUE TITLE
[Bug]: Doesn't work with caves and cliffs backport mod

### ISSUE THREAD

**Issue by qqq0201** [TheIllusiveC4/CustomFoV#6]
### Minecraft Version

1.16.5

### What happened?

It doesn't work with cavesandcliffs-1.16.5-7.1.4

### How do you trigger this bug?

Just install it with caves and cliffs mod

### Loader

Forge

### Loader Version

Forge 36.2.22

### Mod Version

customfov-forge-1.16.5-5.1.0.1

**Comment by TheIllusiveC4** [comment]
It looks like the Caves and Cliffs mod is overriding the FoV changes from Custom FoV. This is best showcased by the fact that changing the `fovPermission` value to `"VANILLA"`, which bypasses any modded changes, will produce the correct behavior. This is an issue you should bring up with those developers, as there's not much I can do about it on my end from what I can tell.

**Comment by qqq0201** [comment]
thanks, that's solve my problem
