### ISSUE TITLE
[Bug]: Crash at start up Minecraft 1.19.1 Forge 42.0.9

### ISSUE THREAD

**Issue by IskallDoe** [TheIllusiveC4/CustomFoV#7]
### Minecraft Version

1.19.2

### What happened?

The game crashes at start up when the mod is installed

### How do you trigger this bug?

1. Install the mod
2. Launch game

Mod list: https://paste.ee/p/spcuj

### Loader

Forge

### Loader Version

Forge 42.0.9

### Mod Version

Custom FoV  6.0.0-beta.1+1.19.2

### Relevant Log Outputs

https://paste.ee/p/AtnEq

**Comment by TheIllusiveC4** [comment]
The issue is that you're trying to use Patchouli, which is only for 1.19.2. For some reason the crash points to Custom FoV as the issue, but that will go away once you've removed any mods that aren't supported for your version.
