### ISSUE TITLE
[Bug]: doesnt work with fabulously optimized

### ISSUE THREAD

**Issue by LhymeFruit** [TheIllusiveC4/CustomFoV#9]
### Minecraft Version

1.19.2

### What happened?

the fov settings just dont show up

### How do you trigger this bug?

1.open video settings
2.open video settings
3.open video settings
...open video settings

### Loader

Fabric

### Loader Version

0.14.9

### Mod Version

the newest idk

**Comment by TheIllusiveC4** [comment]
It seems like a mod is just replacing the video settings, which would explain why Custom FOV's settings don't show up. However, you can still access them through the Accessibility Settings, which I have confirmed myself with the modpack.
